const BackstoryActions = {  
    SET_EVERYTHING: 'SET_EVERYTHING',
    PERSONAL_DESCRIPTION: "SET_PERSONAL_DESCRIPTION",
    TRAITS: "SET_TRAITS",
    IDEOLOGY_BELIEFS: "SET_IDEOLOGY_BELIEFS",
    INJURIES_SCARS: "SET_INJURIES_SCARS",
    SIGNIFICANT_PEOPLE: "SET_SIGNIFICANT_PEOPLE",
    PHOBIAS_MANIAS: "SET_PHOBIAS_MANIAS",
    MEANINGFUL_LOCATIONS: "SET_MEANINGFUL_LOCATIONS",
    ARCANE_TOMES_SPELLS_ARTIFACTS: "SET_ARCANE_TOMES_SPELLS_ARTIFACTS",
    TREASURED_POSSESSIONS: "SET_TREASURED_POSSESSIONS",
    ENCOUNTERS_WITH_STRANGE_ENTITIES: "SET_ENCOUNTERS_WITH_STRANGE_ENTITIES"
}

export default BackstoryActions;