const GameHostActions = {
    SET_PORT: "SET_PORT",
    SET_ROOM_CODE: "SET_ROOM_CODE",
    SET_PLAYER_DATA: "SET_PLAYER_DATA",
    REMOVE_PLAYER_DATA: "REMOVE_PLAYER_DATA",
    SET_CHAT_MESSAGES: "SET_CHAT_MESSAGES",
    SET_HOST_IP: "SET_HOST_IP",
    SET_WEBSOCKET: "SET_WEBSOCKET",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
}

export default GameHostActions;