const InvestigatorSkillsActions = {
    ACCOUNTING: {
        SET_CHECKED: 'SET_ACCOUNTING_CHECKED',
        SET_VALUE: 'SET_ACCOUNTING_VALUE'
    },
    FAST_TALK: {
        SET_CHECKED: 'SET_FAST_TALK_CHECKED',
        SET_VALUE: 'SET_FAST_TALK_VALUE'
    },
    LAW: {
        SET_CHECKED: 'SET_LAW_CHECKED',
        SET_VALUE: 'SET_LAW_VALUE'
    },
    SCIENCE: {
        SET_CHECKED: 'SET_SCIENCE_CHECKED',
        SET_VALUE: 'SET_SCIENCE_VALUE',
        SET_CUSTOM_TEXT: 'SET_SCIENCE_CUSTOM_TEXT'
    },
    ANTHROPOLOGY: {
        SET_CHECKED: 'SET_ANTHROPOLOGY_CHECKED',
        SET_VALUE: 'SET_ANTHROPOLOGY_VALUE'
    },
    FIGHTING_BRAWL: {
        SET_CHECKED: 'SET_FIGHTING_BRAWL_CHECKED',
        SET_VALUE: 'SET_FIGHTING_BRAWL_CHECKED'
    },
    LIBRARY_USE: {
        SET_CHECKED: 'SET_LIBRARY_USE_CHECKED',
        SET_VALUE: 'SET_LIBRARY_USE_VALUE'
    },
    CUSTOM_1: {
        SET_CHECKED: 'SET_CUSTOM_1_CHECKED',
        SET_VALUE: 'SET_CUSTOM_1_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_1_CUSTOM_TEXT'
    },
    CUSTOM_2: {
        SET_CHECKED: 'SET_CUSTOM_2_CHECKED',
        SET_VALUE: 'SET_CUSTOM_2_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_2_CUSTOM_TEXT'
    },
    CUSTOM_3: {
        SET_CHECKED: 'SET_CUSTOM_3_CHECKED',
        SET_VALUE: 'SET_CUSTOM_3_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_3_CUSTOM_TEXT'
    },
    CUSTOM_4: {
        SET_CHECKED: 'SET_CUSTOM_4_CHECKED',
        SET_VALUE: 'SET_CUSTOM_4_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_4_CUSTOM_TEXT'
    },
    CUSTOM_5: {
        SET_CHECKED: 'SET_CUSTOM_5_CHECKED',
        SET_VALUE: 'SET_CUSTOM_5_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_5_CUSTOM_TEXT'
    },
    CUSTOM_6: {
        SET_CHECKED: 'SET_CUSTOM_6_CHECKED',
        SET_VALUE: 'SET_CUSTOM_6_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_6_CUSTOM_TEXT'
    },
    CUSTOM_7: {
        SET_CHECKED: 'SET_CUSTOM_7_CHECKED',
        SET_VALUE: 'SET_CUSTOM_7_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_7_CUSTOM_TEXT'
    },
    CUSTOM_8: {
        SET_CHECKED: 'SET_CUSTOM_8_CHECKED',
        SET_VALUE: 'SET_CUSTOM_8_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_8_CUSTOM_TEXT'
    },
    CUSTOM_9: {
        SET_CHECKED: 'SET_CUSTOM_9_CHECKED',
        SET_VALUE: 'SET_CUSTOM_9_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_9_CUSTOM_TEXT'
    },
    CUSTOM_10: {
        SET_CHECKED: 'SET_CUSTOM_10_CHECKED',
        SET_VALUE: 'SET_CUSTOM_10_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_10_CUSTOM_TEXT'
    },
    CUSTOM_11: {
        SET_CHECKED: 'SET_CUSTOM_11_CHECKED',
        SET_VALUE: 'SET_CUSTOM_11_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_11_CUSTOM_TEXT'
    },
    CUSTOM_12: {
        SET_CHECKED: 'SET_CUSTOM_12_CHECKED',
        SET_VALUE: 'SET_CUSTOM_12_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_12_CUSTOM_TEXT'
    },
    CUSTOM_13: {
        SET_CHECKED: 'SET_CUSTOM_13_CHECKED',
        SET_VALUE: 'SET_CUSTOM_13_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_13_CUSTOM_TEXT'
    },
    CUSTOM_14: {
        SET_CHECKED: 'SET_CUSTOM_14_CHECKED',
        SET_VALUE: 'SET_CUSTOM_14_VALUE',
        SET_CUSTOM_TEXT: 'SET_CUSTOM_14_CUSTOM_TEXT'
    },
    APPRAISE: {
        SET_CHECKED: 'SET_APPRAISE_CHECKED',
        SET_VALUE: 'SET_APPRAISE_VALUE'
    },
    LISTEN: {
        SET_CHECKED: 'SET_LISTEN_CHECKED',
        SET_VALUE: 'SET_LISTEN_VALUE'
    },
    ARCHAEOLOGY: {
        SET_CHECKED: 'SET_ARCHAEOLOGY_CHECKED',
        SET_VALUE: 'SET_ARCHAEOLOGY_VALUE'
    },
    LOCKSMITH: {
        SET_CHECKED: 'SET_LOCKSMITH_CHECKED',
        SET_VALUE: 'SET_LOCKSMITH_VALUE'
    },
    SLEIGHT_OF_HAND: {
        SET_CHECKED: 'SET_SLEIGHT_OF_HAND_CHECKED',
        SET_VALUE: 'SET_SLEIGHT_OF_HAND_VALUE'
    },
    ART_CRAFT: {
        SET_CHECKED: 'SET_ART_CRAFT_CHECKED',
        SET_VALUE: 'SET_ART_CRAFT_CHECKED',
        SET_CUSTOM_TEXT: 'SET_ART_CRAFT_CUSTOM_TEXT'
    },
    FIREARMS_HANDGUN: {
        SET_CHECKED: 'SET_FIREARMS_HANDGUN_CHECKED',
        SET_VALUE: 'SET_FIREARMS_HANDGUN_VALUE'
    },
    MECH_REPAIR: {
        SET_CHECKED: 'SET_MECH_REPAIR_CHECKED',
        SET_VALUE: 'SET_MECH_REPAIR_VALUE'
    },
    SPOT_HIDDEN: {
        SET_CHECKED: 'SET_SPOT_HIDDEN_CHECKED',
        SET_VALUE: 'SET_SPOT_HIDDEN_VALUE'
    },
    FIREARMS_RIFLE_SHOTGUN: {
        SET_CHECKED: 'SET_FIREARMS_RIFLE_SHOTGUN_CHECKED',
        SET_VALUE: 'SET_FIREARMS_RIFLE_SHOTGUN_VALUE'
    },
    MEDICINE: {
        SET_CHECKED: 'SET_MEDICINE_CHECKED',
        SET_VALUE: 'SET_MEDICINE_VALUE'
    },
    STEALTH: {
        SET_CHECKED: 'SET_STEALTH_CHECKED',
        SET_VALUE: 'SET_STEALTH_VALUE'
    },
    NATURAL_WORLD: {
        SET_CHECKED: 'SET_NATURAL_WORLD_CHECKED',
        SET_VALUE: 'SET_NATURAL_WORLD_VALUE'
    },
    SURVIVAL: {
        SET_CHECKED: 'SET_SURVIVAL_CHECKED',
        SET_VALUE: 'SET_SURVIVAL_VALUE',
        SET_CUSTOM_TEXT: 'SET_SURVIVAL_CUSTOM_TEXT'
    },
    CHARM: {
        SET_CHECKED: 'SET_CHARM_CHECKED',
        SET_VALUE: 'SET_CHARM_VALUE'
    },
    FIRST_AID: {
        SET_CHECKED: 'SET_FIRST_AID_CHECKED',
        SET_VALUE: 'SET_FIRST_AID_VALUE'
    },
    NAVIGATE: {
        SET_CHECKED: 'SET_NAVIGATE_CHECKED',
        SET_VALUE: 'SET_NAVIGATE_VALUE'
    },
    SWIM: {
        SET_CHECKED: 'SET_SWIM_CHECKED',
        SET_VALUE: 'SET_SWIM_VALUE'
    },
    CLIMB: {
        SET_CHECKED: 'SET_CLIMB_CHECKED',
        SET_VALUE: 'SET_CLIMB_VALUE'
    },
    HISTORY: {
        SET_CHECKED: 'SET_HISTORY_CHECKED',
        SET_VALUE: 'SET_HISTORY_VALUE'
    },
    OCCULT: {
        SET_CHECKED: 'SET_OCCULT_CHECKED',
        SET_VALUE: 'SET_OCCULT_VALUE'
    },
    THROW: {
        SET_CHECKED: 'SET_THROW_CHECKED',
        SET_VALUE: 'SET_THROW_VALUE'
    },
    CREDIT_RATING: {
        SET_VALUE: 'SET_CREDIT_RATING_VALUE'
    },
    INTIMIDATE: {
        SET_CHECKED: 'SET_INTIMIDATE_CHECKED',
        SET_VALUE: 'SET_INTIMIDATE_VALUE'
    },
    OP_HV_MACHINE: {
        SET_CHECKED: 'SET_OP_HV_MACHINE_CHECKED',
        SET_VALUE: 'SET_OP_HV_MACHINE_VALUE'
    },
    TRACK: {
        SET_CHECKED: 'SET_TRACK_CHECKED',
        SET_VALUE: 'SET_TRACK_VALUE'
    },
    CTHULHU_MYTHOS: {
        SET_VALUE: 'SET_CTHULHU_MYTHOS_VALUE'
    },
    JUMP: {
        SET_CHECKED: 'SET_JUMP_CHECKED',
        SET_VALUE: 'SET_JUMP_VALUE'
    },
    PERSUADE: {
        SET_CHECKED: 'SET_PERSUADE_CHECKED',
        SET_VALUE: 'SET_PERSUADE_VALUE'
    },
    DISGUISE: {
        SET_CHECKED: 'SET_DISGUISE_CHECKED',
        SET_VALUE: 'SET_DISGUISE_VALUE'
    },
    LANGUAGE_OTHER: {
        SET_CHECKED: 'SET_LANGUAGE_OTHER_CHECKED',
        SET_VALUE: 'SET_LANGUAGE_OTHER_VALUE',
        SET_CUSTOM_TEXT: 'SET_LANGUAGE_OTHER_VALUE_CUSTOM_TEXT'
    },
    PILOT: {
        SET_CHECKED: 'SET_PILOT_CHECKED',
        SET_VALUE: 'SET_PILOT_VALUE',
        SET_CUSTOM_TEXT: 'SET_PILOT_CUSTOM_TEXT'
    },
    DODGE: {
        SET_CHECKED: 'SET_DODGE_CHECKED',
    },
    PSYCHOLOGY: {
        SET_CHECKED: 'SET_PSYCHOLOGY_CHECKED',
        SET_VALUE: 'SET_PSYCHOLOGY_VALUE'
    },
    DRIVE_AUTO: {
        SET_CHECKED: 'SET_DRIVE_AUTO_CHECKED',
        SET_VALUE: 'SET_DRIVE_AUTO_VALUE'
    },
    PSYCHOANALYSIS: {
        SET_CHECKED: 'SET_PSYCHOANALYSIS_CHECKED',
        SET_VALUE: 'SET_PSYCHOANALYSIS_VALUE'
    },
    ELEC_REPAIR: {
        SET_CHECKED: 'SET_ELEC_REPAIR_CHECKED',
        SET_VALUE: 'SET_ELEC_REPAIR_VALUE'
    },
    LANGUAGE_OWN: {
        SET_CHECKED: 'SET_LANGUAGE_OWN_CHECKED',
        SET_VALUE: 'SET_LANGUAGE_OWN_VALUE'
    },
    RIDE: {
        SET_CHECKED: 'SET_RIDE_CHECKED',
        SET_VALUE: 'SET_RIDE_VALUE'
    }
}

export default InvestigatorSkillsActions;