const WeaponsAndGearActions = {
    SET_EVERYTHING: 'SET_EVERYTHING',
    SET_WEAPON: {
        WEAPON1: {
            NAME: "SET_WEAPON1_NAME",
            REGULAR: "SET_WEAPON1_REGULAR",
            HARD: "SET_WEAPON1_HARD",
            EXTREME: "SET_WEAPON1_EXTREME",
            DAMAGE: "SET_WEAPON1_DAMAGE",
            RANGE: "SET_WEAPON1_RANGE",
            ATTACKS: "SET_WEAPON1_ATTACKS",
            AMMO: "SET_WEAPON1_AMMO",
            MALF: "SET_WEAPON1_MALF"
        },
        WEAPON2: {
            NAME: "SET_WEAPON2_NAME",
            REGULAR: "SET_WEAPON2_REGULAR",
            HARD: "SET_WEAPON2_HARD",
            EXTREME: "SET_WEAPON2_EXTREME",
            DAMAGE: "SET_WEAPON2_DAMAGE",
            RANGE: "SET_WEAPON2_RANGE",
            ATTACKS: "SET_WEAPON2_ATTACKS",
            AMMO: "SET_WEAPON2_AMMO",
            MALF: "SET_WEAPON2_MALF"
        },
        WEAPON3: {
            NAME: "SET_WEAPON3_NAME",
            REGULAR: "SET_WEAPON3_REGULAR",
            HARD: "SET_WEAPON3_HARD",
            EXTREME: "SET_WEAPON3_EXTREME",
            DAMAGE: "SET_WEAPON3_DAMAGE",
            RANGE: "SET_WEAPON3_RANGE",
            ATTACKS: "SET_WEAPON3_ATTACKS",
            AMMO: "SET_WEAPON3_AMMO",
            MALF: "SET_WEAPON3_MALF"
        },
        WEAPON4: {
            NAME: "SET_WEAPON4_NAME",
            REGULAR: "SET_WEAPON4_REGULAR",
            HARD: "SET_WEAPON4_HARD",
            EXTREME: "SET_WEAPON4_EXTREME",
            DAMAGE: "SET_WEAPON4_DAMAGE",
            RANGE: "SET_WEAPON4_RANGE",
            ATTACKS: "SET_WEAPON4_ATTACKS",
            AMMO: "SET_WEAPON4_AMMO",
            MALF: "SET_WEAPON4_MALF"
        },
        WEAPON5: {
            NAME: "SET_WEAPON5_NAME",
            REGULAR: "SET_WEAPON5_REGULAR",
            HARD: "SET_WEAPON5_HARD",
            EXTREME: "SET_WEAPON5_EXTREME",
            DAMAGE: "SET_WEAPON5_DAMAGE",
            RANGE: "SET_WEAPON5_RANGE",
            ATTACKS: "SET_WEAPON5_ATTACKS",
            AMMO: "SET_WEAPON5_AMMO",
            MALF: "SET_WEAPON5_MALF"
        },
    },
    SET_GEAR_AND_POSSESSIONS: {
        GEAR_AND_POSSESSIONS_1: "SET_GEAR_AND_AND_POSSESSIONS1",
        GEAR_AND_POSSESSIONS_2: "SET_GEAR_AND_AND_POSSESSIONS2",
        GEAR_AND_POSSESSIONS_3: "SET_GEAR_AND_AND_POSSESSIONS3",
        GEAR_AND_POSSESSIONS_4: "SET_GEAR_AND_AND_POSSESSIONS4",
        GEAR_AND_POSSESSIONS_5: "SET_GEAR_AND_AND_POSSESSIONS5",
        GEAR_AND_POSSESSIONS_6: "SET_GEAR_AND_AND_POSSESSIONS6",
        GEAR_AND_POSSESSIONS_7: "SET_GEAR_AND_AND_POSSESSIONS7",
        GEAR_AND_POSSESSIONS_8: "SET_GEAR_AND_AND_POSSESSIONS8",
        GEAR_AND_POSSESSIONS_9: "SET_GEAR_AND_AND_POSSESSIONS9",
        GEAR_AND_POSSESSIONS_10: "SET_GEAR_AND_AND_POSSESSIONS10",
        GEAR_AND_POSSESSIONS_11: "SET_GEAR_AND_AND_POSSESSIONS11",
        GEAR_AND_POSSESSIONS_12: "SET_GEAR_AND_AND_POSSESSIONS12",
        GEAR_AND_POSSESSIONS_13: "SET_GEAR_AND_AND_POSSESSIONS13",
        GEAR_AND_POSSESSIONS_14: "SET_GEAR_AND_AND_POSSESSIONS14",
        GEAR_AND_POSSESSIONS_15: "SET_GEAR_AND_AND_POSSESSIONS15",
        GEAR_AND_POSSESSIONS_16: "SET_GEAR_AND_AND_POSSESSIONS16",
        GEAR_AND_POSSESSIONS_17: "SET_GEAR_AND_AND_POSSESSIONS17",
        GEAR_AND_POSSESSIONS_18: "SET_GEAR_AND_AND_POSSESSIONS18",
        GEAR_AND_POSSESSIONS_19: "SET_GEAR_AND_AND_POSSESSIONS19",
        GEAR_AND_POSSESSIONS_20: "SET_GEAR_AND_AND_POSSESSIONS20",
    },
    SET_CASH_AND_ASSETS: {
        SPENDING_LEVEL: "SET_SPENDING_LEVEL",
        CASH: "SET_CASH",
        ASSETS: {
            SET_ASSET1: "SET_ASSET1",
            SET_ASSET2: "SET_ASSET2",
            SET_ASSET3: "SET_ASSET3",
            SET_ASSET4: "SET_ASSET4",
            SET_ASSET5: "SET_ASSET5",
            SET_ASSET6: "SET_ASSET6",
            SET_ASSET7: "SET_ASSET7",
            SET_ASSET8: "SET_ASSET8"
        }
    }
}

export default WeaponsAndGearActions;