const HostedGameActions = {
    CONNECT_TO_HOST: 'CONNECT_TO_HOST',
    SET_ROOM_CODE: 'SET_ROOM_CODE',
    SET_SOCKET_ADDRESS: 'SET_SOCKET_ADDRESS',
    SEND_PLAYER_DATA: 'SEND_PLAYER_DATA',
    SET_CHAT_MESSAGES: 'SET_CHAT_MESSAGES',
    SET_PLAYER_NAME: 'SET_PLAYER_NAME',
    SET_PLAYER_ID: 'SET_PLAYER_ID',
    SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',
    DISCONNECT_FROM_HOST: 'DISCONNECT_FROM_HOST',
}

export default HostedGameActions;