const actions = {
    SET_CLIENT: "CHANGE_CLIENT_TO",
    SET_CHARACTER_INFO: {
        ALL: "SET_CHARACTER_INFO_ALL",
        NAME: "SET_CHARACTER_INFO_NAME",
        PLAYER: "SET_CHARACTER_INFO_PLAYER",
        OCCUPATICE: "SET_CHARACTER_INFO_OCCUPATICE",
        AGE: "SET_CHARACTER_INFO_AGE",
        SEX: "SET_CHARACTER_INFO_SEX",
        RESIDENCE: "SET_CHARACTER_INFO_RESIDENCE",
        BIRTHPLACE: "SET_CHARACTER_INFO_BIRTHPLACE",
    },
    SET_CHARACTERISTICS: {
        ALL: "SET_CHARACTERISTICS_ALL",
        STR: "SET_CHARACTERISTICS_STR",
        DEX: "SET_CHARACTERISTICS_DEX",
        POW: "SET_CHARACTERISTICS_POW",
        CON: "SET_CHARACTERISTICS_CON",
        APP: "SET_CHARACTERISTICS_APP",
        EDU: "SET_CHARACTERISTICS_EDU",
        SIZ: "SET_CHARACTERISTICS_SIZ",
        INT: "SET_CHARACTERISTICS_INT",
        MOVE: "SET_CHARACTERISTICS_MOVE"
    }
}

export default actions;