const ageMods = [
    [19,"Deduct <b>5</b> points among STR and SIZ. Deduct <b>5</b> points from EDU. Roll <b>3d6*5</b> twice to generate a Luck score and use the higher value.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
    [39,"Make an improvement check for EDU by rolling <b>1d100</b>, if the result is higher than your current EDU, add <b>1d10</b> amount of points to your current EDU.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
    [49,"Make <b>2</b> improvement checks for EDU by rolling <b>1d100</b>, if the result is higher than your current EDU, add <b>1d10</b> amount of points to your current EDU, and deduct <b>5</b> points among STR, CON or DEX, and reduce APP by <b>5</b>.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
    [59,"Make <b>3</b> improvement checks for EDU by rolling <b>1d100</b>, if the result is higher than your current EDU, add <b>1d10</b> amount of points to your current EDU, and deduct <b>10</b> points among STR, CON or DEX, and reduce APP by <b>10</b>.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
    [69,"Make <b>4</b> improvement checks for EDU by rolling <b>1d100</b>, if the result is higher than your current EDU, add <b>1d10</b> amount of points to your current EDU, and deduct <b>20</b> points among STR, CON or DEX, and reduce APP by <b>15</b>.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
    [79,"Make <b>4</b> improvement checks for EDU by rolling <b>1d100</b>, if the result is higher than your current EDU, add <b>1d10</b> amount of points to your current EDU, and deduct <b>40</b> points among STR, CON or DEX, and reduce APP by <b>20</b>.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
    [89,"Make <b>4</b> improvement checks for EDU by rolling <b>1d100</b>, if the result is higher than your current EDU, add <b>1d10</b> amount of points to your current EDU, and deduct <b>80</b> points among STR, CON or DEX, and reduce APP by <b>25</b>.<p><i>(Note that maximum EDU is <b>99</b>)</i></p>"],
];

module.exports = ageMods;